ruby '2.1.5'
source 'https://rubygems.org'

gem 'sinatra'
gem 'httparty'
gem 'json'
gem 'capistrano'
gem 'puma'
gem 'cineaste', '0.0.1.2', git: "https://github.com/xenophin/cineaste"

gem 'aws-sdk', '2.0.6.pre'




